// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import "forge-std/Script.sol";
import {TreasureHunt} from "../src/TreasureHunt.sol";
import {HonkVerifier} from "../src/Verifier.sol"; 


// Script to deploy the TreasureHunt contract.
//
// The Verifier.sol is generated by Barrettenberg's Honk backend using `build.sh` script.
// For the upcoming snorkeling treausure hunt we place 10 treasures in the ocean in
// specified locations. Each treasure is associated with a unique hash (the "treasureHash") that serves as its identifier. To claim a treasure, a participant must find it and generate a ZK proof that they have found the treasure, without revealing its location. The proof is generated off-chain using the Noir circuit and Barrettenberg's Honk backend, and then submitted to the TreasureHunt contract on-chain. The contract verifies the proof using the HonkVerifier, and if valid, transfers the reward to the claimant.
// Secret Treasures for the snorkeling hunt (not revealed to the public):
//      1, 2, 3, 4, 5, 6, 7, 8, 9, 10
// Treasures' hashes (revealed to the public, used as public inputs for the proof generation):
//     1505662313093145631275418581390771847921541863527840230091007112166041775502,
//    -7876059170207639417138377068663245559360606207000570753582208706879316183353,
//    -5602859741022561807370900516277986970516538128871954257532197637239594541050,
//    2256689276847399345359792277406644462014723416398290212952821205940959307205,
//    10311210168613568792124008431580767227982446451742366771285792060556636004770,
//    -5697637861416433807484703347699404695743570043365849280798663758395067508,
//    -2009295789879562882359281321158573810642695913475210803991480097462832104806,
//    8931814952839857299896840311953754931787080333405300398787637512717059406908,
//    -4417726114039171734934559783368726413190541565291523767661452385022043124552,
//    -961435057317293580094826482786572873533235701183329831124091847635547871092 
// Note: The TreasureHunt contract requires funding at deployment, so we send 100 ETH
// in the constructor.
//
// Run with: `forge script Deploy.s.sol --rpc-url http://127.0.0.1:8545  --broadcast`
// in Anvil environment.
// Select appropriate RPC URL for the mainnet.



contract Deploy is Script {

    uint256 constant DEFAULT_INITIAL_FUNDING = 100 ether;
    HonkVerifier verifier;
    TreasureHunt hunt;


    function run() external {
        
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        uint256 initialFunding = vm.envOr("INITIAL_FUNDING", DEFAULT_INITIAL_FUNDING);

        address deployer = vm.addr(deployerKey);

        console2.log("Chain ID:", block.chainid);
        console2.log("Deployer:", deployer);
        console2.log("Deployer balance:", deployer.balance);
        console2.log("Initial funding:", initialFunding);

        vm.startBroadcast(deployerKey);

        verifier = new HonkVerifier();
        hunt = new TreasureHunt{value: initialFunding}(address(verifier));

        vm.stopBroadcast();

        vm.label(address(verifier), "HonkVerifier");
        vm.label(address(hunt), "TreasureHunt");

        require(address(verifier) != address(0), "INVALID_VERIFIER_DEPLOY");
        require(address(hunt) != address(0), "INVALID_HUNT_DEPLOY");
        require(hunt.getContractBalance() == initialFunding, "UNEXPECTED_BALANCE");

        console2.log("Verifier:", address(verifier));
        console2.log("TreasureHunt:", address(hunt));
        console2.log("Balance:", hunt.getContractBalance());
        console2.log("Reward:", hunt.REWARD());
        console2.log("Max treasures:", hunt.MAX_TREASURES());
        console2.log("Remaining treasures:", hunt.getRemainingTreasures());
        console2.log("Paused:", hunt.isPaused());
    }

    
}